### ISSUE TITLE
Fails to import Python package `archivextract` when trying to index a ZIP

### ISSUE THREAD

**Issue by 5jt** [nailuoGG/homebrew-recoll#9]
MacBook Air 2022 macOS 15.1 Sequoia

```txt
❯ recollindex
:2:../common/rclconfig.cpp:373::Copying the backends file: open /Applications/Recoll.app/Contents/Resources/examples/backends: No such file or directoryTraceback (most recent call last):
  File "/Applications/Recoll.app/Contents/Resources/filters/rclzip.py", line 28, in <module>
    from archivextract import ArchiveExtractor
ModuleNotFoundError: No module named 'archivextract'
Traceback (most recent call last):
  File "/Applications/Recoll.app/Contents/Resources/filters/rclzip.py", line 28, in <module>
    from archivextract import ArchiveExtractor
ModuleNotFoundError: No module named 'archivextract'
```
[index.log](https://github.com/user-attachments/files/17592248/index.log)
[errors.log](https://github.com/user-attachments/files/17592249/errors.log)
[corpus.zip](https://github.com/user-attachments/files/17592259/corpus.zip)

**Comment by 5jt** [comment]
From: Jean-Francois Dockes <jf@dockes.org>
    Subject: Re: Missing matches in query results on macOS Apple Silicon; in Python, unable to import archivextract or recoll
    Date: 2 November 2024 at 08:35:12 GMT
    To: Stephen Taylor <sjt@dyalog.com>

    ...

    Oops yes, there are two files missing from the Mac install, this will be fixed in the next
    release. Meanwhile you can fix this by copying archivextract.py and rclnamefilter.py from
    the recoll src/filters source directory to your recoll installation "filters"
    directory. Not sure where these are with homebrew, maybe /opt/local/share/recoll/filters,
    or /usr/local/share/recoll/filters

**Comment by nailuoGG** [comment]
Fixed by #21 (merged). Python extension path and version issues resolved.
